# Generated by Django 5.2.1 on 2025-05-17 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litreview', '0002_alter_review_body_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollows',
            options={'verbose_name_plural': 'User Follows'},
        ),
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='litreview.ticket'),
        ),
    ]
